### ISSUE TITLE
Need to be refactored

### ISSUE THREAD

**Issue by RobTillaart** [RobTillaart/PulsePattern#1]
As PulsePattern is experimental this issue is a placeholder for todo's (also in .cpp file)

###  todo's
- [x] #error if not an AVR platform ==>  #if defined(Arduino) or so?
- [x] get tabs and space right
- [x] #pragma once [done]
- [x] remove pre 1.00 support
- [x] add continue function (after stop)
- ~~function that fetches new value instead of hard array?~~ won't fix is a bit like random example.
- [x] adjust code in setTimer to be more accurate
- [x] low level pin commands => was won't fix as it breaks the path to support ESP, however with #defines this path is still open.
- ~~test invalid array periods (pre-scan in startup)~~  - will not prevent incorrect runtime filling of the array.

### example ideas
- [x] example pulse pattern recorder
- ~~example reading pattern from disk?~~ - works similar as the random example.
